---
- name: Collections & Tests
  block:
    - name: Collect data from /etc/passwd
      ansible.builtin.command:
        cmd: cat /etc/passwd
      changed_when: false
      ignore_errors: true
      register: etc_passwd

    - name: Retrive the remote node IP address
      ansible.builtin.shell:
        cmd: "getent hosts {{ ansible_fqdn }} | awk '{print $1}' | grep -v '127.0' | grep -v '172.17' | grep -v '10.0.2.15' | head -n1"
      changed_when: false
      register: remote_host_ip_address

    - name: Confirm Root .kube directory existance
      ansible.builtin.file:
        mode: 0755
        path: $HOME/.kube
        state: directory

    - name: Confirm Vagrant .kube directory existance
      ansible.builtin.file:
        group: vagrant
        mode: 0755
        owner: vagrant
        path: /home/vagrant/.kube
        state: directory
      when: "etc_passwd.stdout.find('vagrant') != -1"

    - name: Check for kubeadm certificates status
      ansible.builtin.command:
        cmd: kubeadm certs check-expiration
      changed_when: false
      ignore_errors: true
      register: certs_status

- name: Init Kubernetes cluster
  when: "certs_status.stdout.find('MISSING') != -1"
  block:
    - name: Pull images
      ansible.builtin.command:
        cmd: kubeadm config images pull
      changed_when: true
    - name: Kubeadm Init
      ansible.builtin.command:
        cmd: kubeadm init --pod-network-cidr={{ k8s_pods_network_cidr }} --apiserver-advertise-address {{ remote_host_ip_address.stdout_lines[0] }}
      changed_when: true
      register: kubeadm_init_rv
    - name: Show kubeadm init STDOUT
      ansible.builtin.debug:
        msg: "{{ kubeadm_init_rv.stdout_lines }}"
    - name: Show kubeadm init STDERR
      ansible.builtin.debug:
        msg: "{{ kubeadm_init_rv.stderr_lines }}"

- name: Copy ClusterConfiguration to Root home directory
  ansible.builtin.copy:
    dest: $HOME/.kube/config
    mode: 0640
    src: /etc/kubernetes/admin.conf
    remote_src: true
- name: Copy ClusterConfiguration to Vagrant home directory
  ansible.builtin.copy:
    dest: /home/vagrant/.kube/config
    group: vagrant
    mode: 0640
    owner: vagrant
    src: /etc/kubernetes/admin.conf
    remote_src: true
  when: "etc_passwd.stdout.find('vagrant') != -1"
