---
- name: Collections & Tests
  block:
    - name: Check if Calico custom-resources.yaml already exists
      ansible.builtin.stat:
        path: "{{ calico_custom_resources_yaml }}"
      changed_when: false
      register: calico_custom_resources
    - name: Check if Calico is already setup & running
      ansible.builtin.command:
        cmd: "kubectl get pods -n calico-system -l app.kubernetes.io/name=calico-node \
          -o custom-columns=NAME:.metadata.name,NODE_NAME:.spec.nodeName,STATUS:.status.containerStatuses[].state"
      changed_when: false
      ignore_errors: true
      register: calico_system_status
    - name: Confirm Tigera operator pod existance
      ansible.builtin.command:
        cmd: kubectl get -n tigera-operator pods --no-headers=true
      changed_when: false
      ignore_errors: true
      register: tigera_pod

- name: Calico network setup
  when: "calico_system_status.stdout.find('calico') == -1 and calico_system_status.stdout.find('running') == -1"
  block:
    - name: Launch Tigera operator pod
      ansible.builtin.command:
        cmd: kubectl create -f https://raw.githubusercontent.com/projectcalico/calico/v3.25.0/manifests/tigera-operator.yaml
      when: "tigera_pod.stdout.find('tigera-operator') == -1"
    - name: Create Calico directory
      ansible.builtin.file:
        mode: 0755
        path: /opt/k8s/custom_resources/calico
        state: directory
    - name: Download Calico custom-resources.yaml
      ansible.builtin.get_url:
        dest: "{{ calico_custom_resources_yaml }}"
        mode: 0644
        url: https://raw.githubusercontent.com/projectcalico/calico/v3.25.0/manifests/custom-resources.yaml
    - name: Update CIDR subnet in Calico custom resources configuration file
      ansible.builtin.lineinfile:
        backrefs: true
        line: \g<1>\g<2>{{ k8s_pods_network_cidr }}
        path: "{{ calico_custom_resources_yaml }}"
        regexp: '^(.*)(cidr: )192.168.0.0/16'
        state: present
    - name: Launch Calico setup
      ansible.builtin.command:
        cmd: "kubectl apply -f {{ calico_custom_resources_yaml }}"
      when: "not calico_custom_resources.stat.exists"
    - name: Wait for Calico setup to finish up
      ansible.builtin.command:
        cmd: kubectl wait --for condition=Established --all CustomResourceDefinition --namespace=calico-system
      changed_when: false
