- name: Install packages
  ansible.builtin.package:
    name:
      - gnupg2
      - "kubeadm"
      - "kubectl"
      - "kubelet"
    state: present

- name: APT hold packages
  ansible.builtin.dpkg_selections:
    name: "{{ item }}"
    selection: hold
  loop: "{{ kubernetes_apps }}"

- name: Create Kubernetes Sysctl configuration file
  ansible.builtin.lineinfile:
    create: true
    line: "{{ item }}"
    mode: 0644
    path: /etc/sysctl.d/99-kubernetes.conf
    state: present
  loop: "{{ sysctl_lines }}"
  notify: Reload sysctl

- name: Flush handlers
  ansible.builtin.meta: flush_handlers
