---
# tasks file for k8s_setup_role
- name: Configure Containerd
  ansible.builtin.import_tasks: containerd.yaml

- name: Install Kubernetes with the Master role
  ansible.builtin.import_tasks: kubernetes.yaml
