- name: Fetch Kubernetes cluster version
  block:
    - name: Fetch content from URL
      ansible.builtin.uri:
        method: GET
        return_content: true
        url: https://cdn.dl.k8s.io/release/stable.txt
      register: url_result

- name: Install Google repo
  block:
    - name: Add Kubernetes apt-key
      get_url:
        url: "https://pkgs.k8s.io/core:/stable:/{{ url_result.content.split('.')[0:2] | join('.') }}/deb/Release.key"
        dest: /etc/apt/keyrings/kubernetes-apt-keyring.asc
        mode: '0644'

    - name: Add Kubernetes APT repository
      apt_repository:
        repo: "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.asc] https://pkgs.k8s.io/core:/stable:/{{ url_result.content.split('.')[0:2] | join('.') }}/deb/ /"
        state: present
        update_cache: yes
