---
# tasks file for baseline
- name: Install packages
  ansible.builtin.package:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - git
      - golang
      - jq
      - software-properties-common
      - vim
      - wget
    state: present
