- name: Kubernetes masters playbook
  gather_facts: false
  hosts: master
  tasks:
    - name: Reset Kubernetes cluster
      block:
        - name: Kubeadm reset
          ansible.builtin.command:
            cmd: kubeadm reset -f
          changed_when: true
        - name: Delete ClusterConfiguration from Kubernetes directory
          ansible.builtin.file:
            path: /etc/kubernets/admin.conf
            state: absent
        - name: Delete ClusterConfiguration from Root home directory
          ansible.builtin.file:
            path: $HOME/.kube/config
            state: absent
        - name: Collect data from /etc/passwd
          ansible.builtin.command:
            cmd: cat /etc/passwd
          changed_when: false
          ignore_errors: true
          register: etc_passwd
        - name: Delete ClusterConfiguration from Vagrant home directory
          ansible.builtin.file:
            path: /home/vagrant/.kube/config
            state: absent
          when: "etc_passwd.stdout.find('vagrant') != -1"
